### PR TITLE
Create deploy-react-to-test.yaml

### PR DESCRIPTION
**Pull request by kmandryk**
add a new github action which automatically deploys to test upon a closed pull request to the development branch that resulted in a successful merge.

### CODE REVIEW

**Review by arlentees — COMMENTED** [review]
The steps look pretty straightforward here, and please forgive the newbie question but how does this start? Is this a manual process or does this kick off automatically from a merge?

**Comment by kmandryk** [comment]
> The steps look pretty straightforward here, and please forgive the newbie question but how does this start? Is this a manual process or does this kick off automatically from a merge?

At the beginning of the file in the 'on' section, it dictates how this workflow is triggered - in this case, it executes when a pull_request on the develop branch is closed. 
In the 'jobs' section, I've added a conditional that says this should only run if this pull request has merged successfully.

**Review by alex-struk — COMMENTED** [review]
Thank you for looking into this Kaegan, it also gives me an opportunity to better examine the deployment process. Here are some points I came up with:

- What was the historical reason for manual trigger instead of doing it automatically? Are we leaving manual deployment in place? Here are some thoughts..
- I suspect the value of doing it manually was so you can deploy any feature branch to test prior to it being merged into dev. Then I think the purpose of test is for a developer to share a particular feature with others, while the dev branch represents a composite of feature branches that passed the inspection on test. I think we need a space to share features on test, as the feedback from that will dictate the pull request approval process, so it seems we want to keep the manual deploy in place. If that's the case then it might make sense to have another deployment phase, let's call it "staging" that will contain the latest dev branch and would be triggered by this script. One way to improve the manual process could be making it so that the deployment to test happens automatically when a feature branch is pushed with a commit that has some keyword in it, like "[publish]", this way you won't have to go through github actions.
- Does it make sense to block the flow if tests fail at any point? Right now the result of testing is inconsequential, from my understanding: "While unit tests are triggered to run on a Pull Request event, both failed and successful runs are inconsequential to the rest of the deployment process." (from technical report)
- There's a documentation file at https://github.com/bcgov/digital.gov.bc.ca/blob/develop/docs/openshift/deployment-automation.md that would need to reflect the change

Let me know if something is not clear in my ruminations..
Cheers!

**Review by alex-struk — DISMISSED** [review]
Upon further discussion with Kaegan we reached these points:

- Development environment is not fully useful because it lacks strapi, prompting me to dismiss it and requisite an additional environment ("staging")
- If the development environment is fully functional then the deployment process would be:
1. Making a pull request from a feature branch to development branch automatically deploys feature branch to development environment
2. Development environment gets reviewed and the pull request gets approved. This triggers deployment of the development branch to test (NEW)
3. Test environment gets reviewed and a pull request is made from development to master. This is used to publish the development branch to production as before. Once published, the pull request gets approved so that master and production are in sync (in the future probably makes sense to publish master instead of development to production instead?). 
- With regards to making failed tests block the deployment process, what's the best place for that? Would it be possible to block pull request to dev until tests pass?

**Comment by kmandryk** [comment]
As discussed, I think we're good to go ahead with this change - however, there are some issues with the action file, so I will try to fix these before we go ahead with the merge.

**Pull request merged**
