### PR TITLE
Bug/154 breadcrumbs

### PR DESCRIPTION
**Pull request by patricksimonian**
Not perfect but we are getting there. I am having issues with styling the breadcrumbs. 

I was hoping John could take a look into my PR to see what i'm doing wrong!

## SPecial Notes

- abstracted away a generic container for all content outside of the header that is responsive to the header
- abstracted away a generic container for the basic horizontal spacing we need between mobile and larger screen widths called `PaddedContainer`

### CODE REVIEW

**Comment by HeatherRemacle** [comment]
@thegentlemanphysicist  do you know if we addressed

**Comment by thegentlemanphysicist** [comment]
I'll take over the PR and figure out if we should keep it

**Comment by thegentlemanphysicist** [comment]
This was dealing with the bug https://github.com/bcgov/digital.gov.bc.ca/issues/154, it seems to have been addressed. I will still poke around the code to see what else I can do to fix it.

**Comment by thegentlemanphysicist** [comment]
Jon recommends closing this PR

**Pull request closed without merging**
