### PR TITLE
Frontend 477 Styling and Test Coverage

### PR DESCRIPTION
**Pull request by thegentlemanphysicist**
This PR adds tests to the code created in #533. Note it will also be used to merge in any styling changes @singhinderdeep deems necessary to meet design standards.  
Ready for code review.  
- Frontend is [Here](https://digital-gov-frontend-pr-540-c0cce6-dev.apps.silver.devops.gov.bc.ca/cocos/)
- Strapi admin is [Here](https://strapi-pr-540-c0cce6-dev.apps.silver.devops.gov.bc.ca/admin)

### CODE REVIEW

**Review by singhinderdeep — CHANGES_REQUESTED** [review]
For support, text could be Mon-Fri instead of MonFriday. 
Also, didn't we decide that icons will be on top and text on bottom for price, teams, support etc. As of now, price, teams and time are on one line and support on two. Should be consistent for all four.

Have the same comments about typography (already mentioned in #528 

Rest all looks good.

**Comment by thegentlemanphysicist** [comment]
for content completion question: 

Content for sso is pretty complete. We don’t have the metrics, so can hide those fields, and for contact info we can include their rocket chat link
	
That is correct, we don’t have examples for CDOGS yet but can publish without them

[10:05 AM] Miaous, Lada Y
for required fields question:
lets remove the constraint on who else is using this. CDOGS doesn’t have examples yet, but the other details for the coco are good to go and ready to be published

[10:05 AM] Miaous, Lada Y
I don't fully understand the order fields in strapi question

**Comment by singhinderdeep** [comment]
Noting down some observations for Jon to take care of

- On mobile, the last tag of “service” is getting truncated (snapshot attached)
- Start using now button seems little too tight (please refer https://developer.gov.bc.ca/Design-System/Primary-Button)
- Spacing between links for "On this page" section and the tags for common component is off

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist - noting a couple of things on the detail page:

Primary button padding is off:
button padding

Padding should look even, like this:
primary button

See Design System specs: https://developer.gov.bc.ca/Design-System/Primary-Button#css

**Comment by mark-a-wilson** [comment]
In a couple places, the font is too small and isn't BC Sans:

font

**Comment by thegentlemanphysicist** [comment]
> In a couple places, the font is too small and isn't BC Sans:
> 
> font

good eye on that, fixed now.

**Review by parulmishra — APPROVED** [review]

**Pull request merged**
