### PR TITLE
Css 271

### LINKED ISSUE #271: Extra space between the nav bar and hero section on all three case studies pages
Please remove the extra spacing between the nav bar and hero section on all three case studies pages. 
Screen Shot 2020-08-27 at 1 38 26 PM

### PR DESCRIPTION
**Pull request by thegentlemanphysicist**
This PR does 4 things
- The page banners with images have now been integrated into a single common component BannerWithImage, it's content is passed in as props.
- The styling of this component is done entirely in styled-componnents and the now useless css is deleted
- The react component 'Template' was renamed 'CaseStudy' because the term is more descriptive.
- A minor update to the ansible read me to fix a miscommunication.

Fixes #271

### CODE REVIEW

**Review by mark-a-wilson — COMMENTED** [review]
Looks great @thegentlemanphysicist. 

I am looking at the deployment listed on this PR ([325](https://digital-gov-frontend-pr-325-xdwiwd-dev.pathfinder.gov.bc.ca/) for some reason?), and from what I see:

- This fixes the content overlap issue noted in #278 for the pages with banners with images. (To complete #278, need to fix the overlapping for banners without images as well.)
- the gap noted on #271 is still present:

gap

**Comment by thegentlemanphysicist** [comment]
> Looks great @thegentlemanphysicist.
> 
> I am looking at the deployment listed on this PR ([325](https://digital-gov-frontend-pr-325-xdwiwd-dev.pathfinder.gov.bc.ca/) for some reason?), and from what I see:
> 
> * This fixes the content overlap issue noted in #278 for the pages with banners with images. (To complete #278, need to fix the overlapping for banners without images as well.)
> * the gap noted on #271 is still present:
> 
> gap

I think this is related to paruls issue with redeployment not working properly.

**Comment by mark-a-wilson** [comment]
Super - redeployment did the trick - I confirm this fixes #271.

**Review by mark-a-wilson — APPROVED** [review]
Approved!

**Pull request merged**
