### PR TITLE
Blog Implementation 

### PR DESCRIPTION
**Pull request by thegentlemanphysicist**
This is a rough cut of the blog.  
url is at /blog

Missing
- Embedded media not rendering properly
-- ~Fix images with search and replace~
-- Fix the omebed coming from video embedding
- ~default images for cards and on blog page~
- pagination
- ~navigation between blog posts~

### CODE REVIEW

**Review by mark-a-wilson — CHANGES_REQUESTED** [review]
@singhinderdeep -- would appreciate your review on this too.

@thegentlemanphysicist -- here are some things I notice when comparing with the wireframe:

- [x] card text:
card-text

- [x] margin spacing:
margin-spacing

- [x] margin around date:
margin-around-date

- [x] block quote:
blockquote

- [x] styling for the image caption:
figcaption

**Comment by singhinderdeep** [comment]
@thegentlemanphysicist The image on the right card is a bit taller than the one on left. Both needs to be of the same size.
Screen Shot 2021-05-17 at 2 27 43 PM

Card titles are h1 size (31px). In Figma, they are h3 size (Heading 3 - 1.44em (25.92px))

**Review by mark-a-wilson — CHANGES_REQUESTED** [review]
Thanks, looks like all has been fixed except for one thing:

font-size on `<blockquote>` -- the 22px style not being picked up because `<p>` is inside `<blockquote>`)

**Review by mark-a-wilson — APPROVED** [review]
Thank you — that fixes all the issues we identified.

**Pull request merged**
